// Auto-generated by cbindgen. Do not edit manually.
// Copyright 2026 tarnishablec. All Rights Reserved.


#ifndef DWEBBLE_RWS_FFI_H
#define DWEBBLE_RWS_FFI_H

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <cstdint>
#include <cstddef>

/// Result codes for FFI operations
enum class DwebbleResult {
  DWEBBLE_RESULT_OK = 0,
  DWEBBLE_RESULT_INVALID_HANDLE = 1,
  DWEBBLE_RESULT_INVALID_PARAM = 2,
  DWEBBLE_RESULT_ALREADY_RUNNING = 3,
  DWEBBLE_RESULT_NOT_RUNNING = 4,
  DWEBBLE_RESULT_BIND_FAILED = 5,
  DWEBBLE_RESULT_TLS_ERROR = 6,
  DWEBBLE_RESULT_RUNTIME_ERROR = 7,
  DWEBBLE_RESULT_SEND_FAILED = 8,
  DWEBBLE_RESULT_CONNECTION_CLOSED = 9,
};

/// Event types for polling
enum class DwebbleEventType {
  DWEBBLE_EVENT_TYPE_NONE = 0,
  DWEBBLE_EVENT_TYPE_CLIENT_CONNECTED = 1,
  DWEBBLE_EVENT_TYPE_CLIENT_DISCONNECTED = 2,
  DWEBBLE_EVENT_TYPE_MESSAGE_RECEIVED = 3,
  DWEBBLE_EVENT_TYPE_ERROR = 4,
};

/// Server handle (opaque pointer)
using DwebbleServerHandle = void*;

/// Server configuration passed from C++
struct DwebbleServerConfig {
  /// Port to listen on (0 for auto)
  uint16_t port;
  /// Bind address (null-terminated UTF-8)
  const char *bind_address;
  /// Subprotocols (null-terminated, comma-separated)
  const char *subprotocols;
  /// TLS certificate path (null for no TLS)
  const char *tls_cert_path;
  /// TLS private key path
  const char *tls_key_path;
};

/// Event data returned from polling
struct DwebbleEvent {
  DwebbleEventType event_type;
  /// Connection ID (valid for Connected/Disconnected/MessageReceived)
  uint64_t connection_id;
  /// Message data pointer (valid for MessageReceived)
  const uint8_t *data;
  /// Message data length
  uintptr_t data_len;
  /// Error message (valid for Error, null-terminated)
  const char *error_message;
};

/// Connection handle
using DwebbleConnectionId = uint64_t;

extern "C" {

/// Initialize tracing (optional, call once)
 void dwebble_rws_init_tracing() ;

/// Create a new WebSocket server with the given configuration.
/// Returns a server handle or null on failure.
 DwebbleServerHandle dwebble_rws_server_create(const DwebbleServerConfig *config) ;

/// Destroy a server handle and free resources.
 void dwebble_rws_server_destroy(DwebbleServerHandle handle) ;

/// Start the WebSocket server.
 DwebbleResult dwebble_rws_server_start(DwebbleServerHandle handle) ;

/// Stop the WebSocket server.
 DwebbleResult dwebble_rws_server_stop(DwebbleServerHandle handle) ;

/// Poll for the next event. Returns the event in the out parameter.
/// Returns true if an event was available, false otherwise.
 bool dwebble_rws_server_poll(DwebbleServerHandle handle, DwebbleEvent *out_event) ;

/// Send binary data to a specific connection.

DwebbleResult dwebble_rws_server_send(DwebbleServerHandle handle,
                                      DwebbleConnectionId connection_id,
                                      const uint8_t *data,
                                      uintptr_t data_len)
;

/// Send text data to a specific connection.

DwebbleResult dwebble_rws_server_send_text(DwebbleServerHandle handle,
                                           DwebbleConnectionId connection_id,
                                           const char *text)
;

/// Disconnect a specific connection.

DwebbleResult dwebble_rws_server_disconnect(DwebbleServerHandle handle,
                                            DwebbleConnectionId connection_id)
;

/// Get the actual port the server is listening to.
 uint16_t dwebble_rws_server_get_port(DwebbleServerHandle handle) ;

/// Get the number of active connections.
 uintptr_t dwebble_rws_server_get_connection_count(DwebbleServerHandle handle) ;

/// Get server info string. Caller must free with `dwebble_rws_free_string`.
 char *dwebble_rws_server_info(DwebbleServerHandle handle) ;

/// Free a string allocated by this library.
 void dwebble_rws_free_string(char *s) ;

}  // extern "C"

#endif  // DWEBBLE_RWS_FFI_H
