// Copyright 2026 tarnishablec. All Rights Reserved.

// ReSharper disable CppUE4CodingStandardNamingViolationWarning
// ReSharper disable CppUnusedIncludeDirective


#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <cstdint>
#include <cstddef>

/// Result codes for WebSocket FFI operations
enum class DwebbleWSResult {
  Ok = 0,
  InvalidHandle = 1,
  InvalidParam = 2,
  AlreadyRunning = 3,
  NotRunning = 4,
  BindFailed = 5,
  TlsError = 6,
  RuntimeError = 7,
  SendFailed = 8,
  ConnectionClosed = 9,
};

/// WebSocket event types for polling
enum class DwebbleWSEventType {
  None = 0,
  ClientConnected = 1,
  ClientDisconnected = 2,
  MessageReceived = 3,
  Error = 4,
};

/// WebSocket server handle (opaque pointer)
using DwebbleWSServerHandle = void*;

/// WebSocket server configuration passed from C++
struct DwebbleWSServerConfig {
  /// Port to listen on (0 for auto)
  uint16_t port;
  /// Bind address (null-terminated UTF-8)
  const char *bind_address;
  /// Subprotocols (null-terminated, comma-separated)
  const char *subprotocols;
  /// TLS certificate path (null for no TLS)
  const char *tls_cert_path;
  /// TLS private key path
  const char *tls_key_path;
};

/// WebSocket event data returned from polling
struct DwebbleWSEvent {
  DwebbleWSEventType event_type;
  /// Connection ID (valid for Connected/Disconnected/MessageReceived)
  uint64_t connection_id;
  /// Message data pointer (valid for MessageReceived)
  const uint8_t *data;
  /// Message data length
  uintptr_t data_len;
  /// Error message (valid for Error, null-terminated)
  const char *error_message;
};

/// WebSocket connection handle
using DwebbleWSConnectionId = uint64_t;

extern "C" {

/// Initialize tracing (optional, call once)
 void dwebble_rws_init_tracing() ;

/// Create a new WebSocket server with the given configuration.
/// Returns a server handle or null on failure.
///
/// # Safety
///
/// - `config` must be a valid pointer to a `DwebbleWSServerConfig`
/// - All string fields in `config` must be valid null-terminated UTF-8 or null
 DwebbleWSServerHandle dwebble_rws_server_create(const DwebbleWSServerConfig *config) ;

/// Destroy a server handle and free resources.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`, or null
/// - `handle` must not be used after this call
 void dwebble_rws_server_destroy(DwebbleWSServerHandle handle) ;

/// Start the WebSocket server.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
 DwebbleWSResult dwebble_rws_server_start(DwebbleWSServerHandle handle) ;

/// Stop the WebSocket server.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
 DwebbleWSResult dwebble_rws_server_stop(DwebbleWSServerHandle handle) ;

/// Poll for the next event. Returns the event in the out parameter.
/// Returns true if an event was available, false otherwise.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
/// - `out_event` must be a valid pointer to a `DwebbleWSEvent`
 bool dwebble_rws_server_poll(DwebbleWSServerHandle handle, DwebbleWSEvent *out_event) ;

/// Send binary data to a specific connection.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
/// - `data` must be a valid pointer to `data_len` bytes

DwebbleWSResult dwebble_rws_server_send(DwebbleWSServerHandle handle,
                                        DwebbleWSConnectionId connection_id,
                                        const uint8_t *data,
                                        uintptr_t data_len)
;

/// Send text data to a specific connection.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
/// - `text` must be a valid null-terminated UTF-8 string

DwebbleWSResult dwebble_rws_server_send_text(DwebbleWSServerHandle handle,
                                             DwebbleWSConnectionId connection_id,
                                             const char *text)
;

/// Disconnect a specific connection.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`

DwebbleWSResult dwebble_rws_server_disconnect(DwebbleWSServerHandle handle,
                                              DwebbleWSConnectionId connection_id)
;

/// Get the actual port the server is listening to.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
 uint16_t dwebble_rws_server_get_port(DwebbleWSServerHandle handle) ;

/// Get the number of active connections.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
 uintptr_t dwebble_rws_server_get_connection_count(DwebbleWSServerHandle handle) ;

/// Get server info string. Caller must free with `dwebble_rws_free_string`.
///
/// # Safety
///
/// - `handle` must be a valid handle returned by `dwebble_rws_server_create`
 char *dwebble_rws_server_info(DwebbleWSServerHandle handle) ;

/// Free a string allocated by this library.
///
/// # Safety
///
/// - `s` must be a string returned by `dwebble_rws_server_info`, or null
/// - `s` must not be used after this call
 void dwebble_rws_free_string(char *s) ;

}  // extern "C"
